name: CI/CD Derogative Shop

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3
      
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  frontend-check:
    name: Frontend Check
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Code Retrieval
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Dependancies (Frontend)
        run: npm ci

      - name: Tests and Coverage (Frontend)
        run: npm run test:coverage

  backend-check:
    name: Backend Check
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Code Retrieval
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Dependancies (Backend)
        run: npm ci

      - name: Prisma client generation
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma generate

      - name: Tests and Coverage (Backend)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run test:coverage

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  mirror-to-epitech-repo:
      name: Mirror to Epitech Repo
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Mirror push to Epitech
          env:
            TARGET_URL: "https://github.com/EpitechPGE45-2025/G-DER-800-PAR-8-1-derogdev801-4.git"
            TOKEN: ${{ secrets.MIRROR_TOKEN }}
          run: |
            git config --global --unset-all credential.helper || true
            git config --system --unset-all credential.helper || true
            git config --global --add safe.directory /github/workspace
            git remote remove epitech || true
            CLEAN_URL=${TARGET_URL#"https://"}
            echo "Clean URL: $CLEAN_URL"
            AUTH_URL="https://oauth2:${TOKEN}@${CLEAN_URL}"
            git remote add epitech "$AUTH_URL"
            git push --mirror epitech
